Repository Arelle/ixbrl-viewer, pull requests merged in 2022-04, with the labels that each got.

#295 Prevent insertion of script tags if document already contains them
  iXBRLViewerPlugin/__init__.py
  iXBRLViewerPlugin/iXBRLViewer.py
Labels: RM Ready, Merge Requirements Met

#294 Ensure that <script> tags always use default namespace (#282)
  iXBRLViewerPlugin/iXBRLViewer.py
  tests/unit_tests/iXBRLViewerPlugin/test_iXBRLViewer.py
Labels: RM Ready, Merge Requirements Met, InfoSec Review Required

#297 Fix scroll-to-fact in documents with elements with overflowing content
  iXBRLViewerPlugin/viewer/src/js/viewer.js
Labels: Merge Requirements Met

#296 Ignore iXBRL elements that are not in the default target document
  iXBRLViewerPlugin/viewer/src/js/viewer.js
Labels: Merge Requirements Met

#299 Show footnotes on hidden facts
  iXBRLViewerPlugin/viewer/src/js/fact.js
  iXBRLViewerPlugin/viewer/src/js/ixnode.js
  iXBRLViewerPlugin/viewer/src/js/outline.test.js
  iXBRLViewerPlugin/viewer/src/js/viewer.js
  samples/build-viewer.py
  samples/src/ixds-test/document1.html
Labels: RM Ready, Merge Requirements Met
