Repository Arelle/ixbrl-viewer, pull requests merged in 2023-04, with the labels that each got.

#394 Stub viewer mode
  iXBRLViewerPlugin/__init__.py
  iXBRLViewerPlugin/iXBRLViewer.py
  iXBRLViewerPlugin/localviewer.py
  iXBRLViewerPlugin/stubviewer.html
  iXBRLViewerPlugin/viewer/src/js/ixbrlviewer.js
  iXBRLViewerPlugin/viewer/src/js/report.js
  samples/build-viewer.py
Labels: RM Ready, Merge Requirements Met, InfoSec Review Required

#401 Improve load time
  iXBRLViewerPlugin/viewer/src/html/inspector.html
  iXBRLViewerPlugin/viewer/src/i18n/en/translation.json
  iXBRLViewerPlugin/viewer/src/js/inspector.js
  iXBRLViewerPlugin/viewer/src/js/ixbrlviewer.js
  iXBRLViewerPlugin/viewer/src/js/search.js
  iXBRLViewerPlugin/viewer/src/js/util.js
  iXBRLViewerPlugin/viewer/src/js/viewer.js
  iXBRLViewerPlugin/viewer/src/less/form-controls.less
  iXBRLViewerPlugin/viewer/src/less/inspector.less
Labels: RM Ready, Merge Requirements Met

#407 XT-2866 Add ability to filter positive/negative fact values
  iXBRLViewerPlugin/viewer/src/html/inspector.html
  iXBRLViewerPlugin/viewer/src/js/fact.js
  iXBRLViewerPlugin/viewer/src/js/inspector.js
  iXBRLViewerPlugin/viewer/src/js/search.js
  iXBRLViewerPlugin/viewer/src/js/search.test.js
Labels: Merge Requirements Unmet, RM Ready

#403 Switch to class syntax, and other modern JS syntax (viewer.js)
  iXBRLViewerPlugin/viewer/src/js/viewer.js
Labels: Merge Requirements Unmet, RM Ready
