Repository Arelle/ixbrl-viewer, pull requests merged in 2023-05, with the labels that each got.

#415 XT-2867: Filter facts by calculations
  iXBRLViewerPlugin/viewer/src/html/inspector.html
  iXBRLViewerPlugin/viewer/src/js/fact.js
  iXBRLViewerPlugin/viewer/src/js/inspector.js
  iXBRLViewerPlugin/viewer/src/js/report.js
  iXBRLViewerPlugin/viewer/src/js/search.js
  iXBRLViewerPlugin/viewer/src/js/search.test.js
  iXBRLViewerPlugin/viewer/src/less/inspector.less
Labels: RM Ready, Merge Requirements Met

#411 XT-2860 Add ability to download original filing documents to ixbrl-viewer
  iXBRLViewerPlugin/__init__.py
  iXBRLViewerPlugin/constants.py
  iXBRLViewerPlugin/iXBRLViewer.py
  iXBRLViewerPlugin/localviewer.py
  iXBRLViewerPlugin/ui.py
  iXBRLViewerPlugin/viewer/src/js/inspector.js
  iXBRLViewerPlugin/viewer/src/js/menu.js
  iXBRLViewerPlugin/viewer/src/js/report.js
  tests/unit_tests/iXBRLViewerPlugin/test_iXBRLViewer.py
Labels: Merge Requirements Unmet, InfoSec Review Required

#418 XT-2871: Filter facts by concept namespace
  iXBRLViewerPlugin/viewer/src/html/inspector.html
  iXBRLViewerPlugin/viewer/src/js/fact.js
  iXBRLViewerPlugin/viewer/src/js/inspector.js
  iXBRLViewerPlugin/viewer/src/js/report.js
  iXBRLViewerPlugin/viewer/src/js/search.js
  iXBRLViewerPlugin/viewer/src/js/search.test.js
  iXBRLViewerPlugin/viewer/src/less/inspector.less
Labels: RM Ready, Merge Requirements Met

#420 XT-2861 XT-2862 Document Summary Pane
  iXBRLViewerPlugin/iXBRLViewer.py
  iXBRLViewerPlugin/viewer/src/html/inspector.html
  iXBRLViewerPlugin/viewer/src/i18n/en/translation.json
  iXBRLViewerPlugin/viewer/src/i18n/es/translation.json
  iXBRLViewerPlugin/viewer/src/js/concept.js
  iXBRLViewerPlugin/viewer/src/js/inspector.js
  iXBRLViewerPlugin/viewer/src/js/report.js
  iXBRLViewerPlugin/viewer/src/js/summary.js
  iXBRLViewerPlugin/viewer/src/js/summary.test.js
  iXBRLViewerPlugin/viewer/src/less/icons.less
  iXBRLViewerPlugin/viewer/src/less/inspector.less
  iXBRLViewerPlugin/viewer/src/less/summary.less
  tests/unit_tests/iXBRLViewerPlugin/mock_arelle.py
  tests/unit_tests/iXBRLViewerPlugin/test_iXBRLViewer.py
Labels: RM Ready, Merge Requirements Met

#422 XT-2948 - Create puppeteer JS config/smoke test for ixbrl-viewer
  .github/workflows/puppeteer.yml
  .gitignore
  README.md
  package.json
  tests/puppeteer/framework/core_elements.js
  tests/puppeteer/framework/page_objects/doc_frame.js
  tests/puppeteer/framework/page_objects/fact_details_panel.js
  tests/puppeteer/framework/utils.js
  tests/puppeteer/framework/viewer_page.js
  tests/puppeteer/puppeteer_test_run_via_intellij.jpg
  tests/puppeteer/test_filings/filing_documents_smoke_test.zip
  tests/puppeteer/tests/fact_properties.test.js
  tests/puppeteer/tools/generate.sh
Labels: RM Ready, Merge Requirements Met

#426 Add support for Inline XBRL Document Sets in GUI (use Stub Viewer mode)
  iXBRLViewerPlugin/__init__.py
Labels: RM Ready, Merge Requirements Met

#428 Fix error trying to get a prefix for a footnote
  iXBRLViewerPlugin/viewer/src/js/report.js
Labels: Merge Requirements Unmet, RM Ready

#429 XT-2874 XT-2875 Add filter on dimension type
  iXBRLViewerPlugin/viewer/src/html/inspector.html
  iXBRLViewerPlugin/viewer/src/js/fact.js
  iXBRLViewerPlugin/viewer/src/js/inspector.js
  iXBRLViewerPlugin/viewer/src/js/report.js
  iXBRLViewerPlugin/viewer/src/js/search.js
  iXBRLViewerPlugin/viewer/src/js/search.test.js
Labels: RM Ready, Merge Requirements Met

#433 XT-2959: Collapsible filter elements
  iXBRLViewerPlugin/viewer/src/html/fact-details.html
  iXBRLViewerPlugin/viewer/src/html/inspector.html
  iXBRLViewerPlugin/viewer/src/i18n/en/translation.json
  iXBRLViewerPlugin/viewer/src/i18n/es/translation.json
  iXBRLViewerPlugin/viewer/src/js/inspector.js
  iXBRLViewerPlugin/viewer/src/js/search.js
  iXBRLViewerPlugin/viewer/src/js/search.test.js
  iXBRLViewerPlugin/viewer/src/less/inspector.less
  tests/puppeteer/framework/page_objects/search_panel.js
Labels: Security Review Required, RM Ready, Merge Requirements Met
