Repository Arelle/ixbrl-viewer, pull requests merged in 2023-02, with the labels that each got.

#366 XT-2741 Provide examples
  README.md
  examples/README.md
  examples/ixbrl-viewer-demo.gif
  examples/workiva-january-2023-8-k-ixbrl-viewer/exhibit31abylawsofworkivai.htm
  examples/workiva-january-2023-8-k-ixbrl-viewer/exhibit31bbylawsofworkivai.htm
  examples/workiva-january-2023-8-k-ixbrl-viewer/ixbrl-viewer.htm
  examples/workiva-january-2023-8-k-ixbrl-viewer/wk-20230109.xsd
  examples/workiva-january-2023-8-k-ixbrl-viewer/wk-20230109_lab.xml
  examples/workiva-january-2023-8-k-ixbrl-viewer/wk-20230109_pre.xml
Labels: request, Merge Requirements Unmet, RM Ready

#367 XT-2742 Add issue and pr templates
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/questions.yml
  .github/ISSUE_TEMPLATE/request.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: request, RM Ready, Merge Requirements Met

#371 Fix the save viewer functionality
  .gitignore
  iXBRLViewerPlugin/__init__.py
  iXBRLViewerPlugin/iXBRLViewer.py
Labels: Merge Requirements Unmet, RM Ready

#381 Add support for arelle pip installed plugin architecture
  iXBRLViewerPlugin/__init__.py
  setup.py
Labels: Merge Requirements Unmet, RM Ready

#376 Provide plugin example
  .gitignore
  PLUGINS.md
  examples/README.md
  examples/example_plugin/README.md
  examples/example_plugin/example-plugin.gif
  examples/example_plugin/extended-viewer.js
  examples/example_plugin/index.js
  examples/example_plugin/package-lock.json
  examples/example_plugin/package.json
  examples/example_plugin/webpack.config.js
Labels: RM Ready, Merge Requirements Met

#388 Support for Ukrainian currency symbols and company identifiers
  iXBRLViewerPlugin/viewer/src/i18n/en/currencies.json
  iXBRLViewerPlugin/viewer/src/js/identifiers.js
  iXBRLViewerPlugin/viewer/src/js/inspector.js
Labels: Merge Requirements Unmet, RM Ready

#387 XT-2765 Pass filenames to docSetFiles
  .gitignore
  iXBRLViewerPlugin/iXBRLViewer.py
  requirements-dev.txt
  tests/unit_tests/iXBRLViewerPlugin/test_iXBRLViewer.py
Labels: RM Ready, Merge Requirements Met
