Repository Arelle/ixbrl-viewer, pull requests merged in 2023-07, with the labels that each got.

#490 XT-3064: Use npm ci
  .github/dependabot.yml
  .github/workflows/node-tests.yml
  .github/workflows/npm-publish.yml
  .github/workflows/puppeteer.yml
  Dockerfile
Labels: Merge Requirements Unmet, RM Ready

#495 XT-3071: Group Dependabot PRs
  .github/dependabot.yml
Labels: RM Ready, Merge Requirements Met

#499 XT-3080 Update stylelint
  .github/dependabot.yml
  iXBRLViewerPlugin/viewer/src/less/inspector.less
  iXBRLViewerPlugin/viewer/src/less/menu.less
  iXBRLViewerPlugin/viewer/src/less/viewer.less
  package-lock.json
  package.json
Labels: RM Ready, Merge Requirements Met

#501 XT-3010: Create Python package workflow
  .github/dependabot.yml
  .github/workflows/node-tests.yml
  .github/workflows/npm-package.yml
  .github/workflows/npm-publish.yml
  .github/workflows/puppeteer.yml
  .github/workflows/python-package.yml
  .github/workflows/python-tests.yml
  README.md
  package-lock.json
  package.json
Labels: RM Ready, Merge Requirements Met

#506 XT-2854: Create release workflow
  .github/release-drafter.yml
  .github/workflows/node-tests.yml
  .github/workflows/python-tests.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release.yml
Labels: RM Ready, Merge Requirements Met

#516 XT-3086: Build viewers with reference to local copy of script
  iXBRLViewerPlugin/__init__.py
  iXBRLViewerPlugin/iXBRLViewer.py
  samples/build-viewer.py
Labels: RM Ready, Merge Requirements Met

#518 XT-3013: Create ixbrl-viewer review mode
  README.md
  examples/review-mode.png
  iXBRLViewerPlugin/viewer/src/js/index.js
  iXBRLViewerPlugin/viewer/src/js/inspector.js
  iXBRLViewerPlugin/viewer/src/js/ixbrlviewer.js
  iXBRLViewerPlugin/viewer/src/js/number-matcher-preprocess.test.js
  iXBRLViewerPlugin/viewer/src/js/number-matcher.js
  iXBRLViewerPlugin/viewer/src/js/number-matcher.test.js
  iXBRLViewerPlugin/viewer/src/js/viewer.js
  iXBRLViewerPlugin/viewer/src/less/viewer.less
  tests/puppeteer/framework/page_objects/toolbar.js
Labels: RM Ready, Merge Requirements Met

#530 XT-3118 - Add review mode highlight puppeteer testing
  tests/puppeteer/framework/page_objects/doc_frame.js
  tests/puppeteer/framework/viewer_page.js
  tests/puppeteer/test_filings/highlights.zip
  tests/puppeteer/tests/highlight.test.js
Labels: RM Ready, Merge Requirements Met

#534 Set Dependabot update frequency to match Arelle
  .github/dependabot.yml
Labels: RM Ready, Merge Requirements Met

#536 Arelle org repo transfer cleanup
  .dockerignore
  .github/PULL_REQUEST_TEMPLATE.md
  .github/dependabot.yml
  .github/workflows/npm-package.yml
  .github/workflows/python-package.yml
  .github/workflows/release.yml
  CODEOWNERS
  Dockerfile
  PLUGINS.md
  README.md
  aviary.yaml
  examples/example_plugin/package-lock.json
  examples/example_plugin/package.json
  package.json
  pyproject.toml
  setup.py
Labels: InfoSec Review Required

#531 XT-3095: Allow enabling review feature at generation time
  README.md
  iXBRLViewerPlugin/__init__.py
  iXBRLViewerPlugin/iXBRLViewer.py
  iXBRLViewerPlugin/viewer/src/js/index.js
  iXBRLViewerPlugin/viewer/src/js/inspector.js
  iXBRLViewerPlugin/viewer/src/js/ixbrlviewer.js
  iXBRLViewerPlugin/viewer/src/js/ixbrlviewer.test.js
  iXBRLViewerPlugin/viewer/src/js/viewer.js
  samples/build-viewer.py
  tests/puppeteer/tests/highlight.test.js
  tests/unit_tests/iXBRLViewerPlugin/test_iXBRLViewer.py
Labels: Merge Requirements Met

#544 Add an option to provide URL to download filing documents.
  iXBRLViewerPlugin/__init__.py
  iXBRLViewerPlugin/iXBRLViewer.py
Labels: minor-release
