Repository Arelle/ixbrl-viewer, pull requests merged in 2023-06, with the labels that each got.

#446 XT-2997: Handle null unit in scale filter
  iXBRLViewerPlugin/viewer/src/js/fact.js
  iXBRLViewerPlugin/viewer/src/js/fact.test.js
Labels: RM Ready, Merge Requirements Met

#456 XT-3016 - Update python image to 3.9-slim-bullseye
  Dockerfile
Labels: Merge Requirements Unmet, RM Ready

#440 Never scroll when selecting a fact by clicking on it
  iXBRLViewerPlugin/viewer/src/js/inspector.js
  iXBRLViewerPlugin/viewer/src/js/viewer.js
Labels: RM Ready, Merge Requirements Met

#455 Improve layout of tag summary table with narrow width / long prefixes
  iXBRLViewerPlugin/viewer/src/html/inspector.html
  iXBRLViewerPlugin/viewer/src/js/inspector.js
  iXBRLViewerPlugin/viewer/src/less/summary.less
Labels: RM Ready, Merge Requirements Met

#463 XT-3035 Update dependabot config
  .github/dependabot.yml
Labels: RM Ready, Merge Requirements Met

#460 XT-2384: Use pyproject.toml to define PyPI package
  .github/workflows/puppeteer.yml
  .github/workflows/python-tests.yml
  .gitignore
  Dockerfile
  MANIFEST.in
  pyproject.toml
  requirements-dev.txt
  requirements.txt
  setup.py
Labels: RM Ready, Merge Requirements Met

#461 XT-2856: Create GitHub workflow to build npm package
  .github/workflows/npm-publish.yml
  package-lock.json
  package.json
Labels: RM Ready, Merge Requirements Met

#468 XT-3043 Create empty shell setup.py to pass Workiva Deploy validation
  setup.py
Labels: RM Ready, Merge Requirements Met

#475 git ignore npm pack artifact
  .gitignore
Labels: RM Ready, Merge Requirements Met

#467 Modernize JavaScript in inspector.js
  iXBRLViewerPlugin/viewer/src/js/identifiers.js
  iXBRLViewerPlugin/viewer/src/js/identifiers.test.js
  iXBRLViewerPlugin/viewer/src/js/inspector.js
  iXBRLViewerPlugin/viewer/src/js/tableExport.js
  iXBRLViewerPlugin/viewer/src/js/viewer.js
Labels: Security Review Required, RM Ready, Merge Requirements Met

#476 Additional test for calling getScaleLabel on facts with no units.
  iXBRLViewerPlugin/viewer/src/js/fact.test.js
Labels: RM Ready, Merge Requirements Met

#483 XT-3054 Workiva build fixes
  .dockerignore
  Dockerfile
  README.md
Labels: RM Ready, Merge Requirements Met
